language: java

jdk:
  - oraclejdk8

# use the latest jdk
addons:
  apt:
    packages:
      - oracle-java8-installer

script:
  - ./gradlew test
  
after_success:
  - bash <(curl -s https://codecov.io/bash)